[package]
name = "sspšg-discord-bot"
version = "0.2.0"
authors = ["František Vojáček <vojacek.fr.2021@ssps.cz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bot"
path = "kod/bot.rs"

[dependencies]
log = "0.4"
env_logger = "0.10"
dotenv = "0.15"
poise = "0.5"
tokio = { version = "1.26", features = ["macros", "rt-multi-thread"] }